databases:
  - name: stars_about_me
    plan: free
    databaseName: stars_about_me_db
    user: andon_goshev

services:
  - type: web
    plan: free
    name: stars_about_me
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn stars_about_me.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stars_about_me
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4