# Generated by Django 5.1.7 on 2025-03-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lucky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=20, unique=True)),
                ('scanned', models.BooleanField(default=False)),
                ('linked_lucky', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_lucky', to='core.lucky')),
            ],
        ),
    ]
