# Generated by Django 5.1.7 on 2025-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lucky',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-23 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-23 12:00:00'),
            preserve_default=False,
        ),
    ]
