# Generated by Django 5.1.7 on 2025-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_elementlucky_famousquotelucky_wisdomlucky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementlucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='famousquotelucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wisdomlucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
    ]
