# Generated by Django 5.1.7 on 2025-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horoscopelucky_alter_elementlucky_lucky_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horoscopelucky',
            unique_together={('zodiac_sign', 'horoscope_type', 'reference_date')},
        ),
    ]
