# Generated by Django 5.1.7 on 2025-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_horoscopelucky'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='horoscope_scan_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
