# Generated by Django 5.1.7 on 2025-04-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_qrcode_horoscope_scan_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='last_horoscope_sign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='last_horoscope_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elementlucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='famousquotelucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wisdomlucky',
            name='lucky_type',
            field=models.CharField(blank=True, choices=[('quote', 'Quote'), ('wisdom', 'Wisdom'), ('element', 'Element')], max_length=20, null=True),
        ),
    ]
