# Generated by Django 5.1.7 on 2025-04-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_qrcode_last_horoscope_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='last_horoscope_content',
        ),
    ]
