# Generated by Django 5.1.7 on 2025-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_qrcode_last_horoscope_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='last_horoscope_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
