# Generated by Django 5.1.7 on 2025-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_qrcode_last_horoscope_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='horoscope_scan_count',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='last_horoscope_content',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='last_horoscope_sign',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='last_horoscope_type',
        ),
    ]
