# Generated by Django 5.1.7 on 2025-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_qrcode_horoscope_scan_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='linked_lucky_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
