# Generated by Django 5.1.7 on 2025-04-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_qrcode_linked_lucky_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='horoscope_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
