# Generated by Django 5.1.7 on 2025-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_horoscopelucky_alter_elementlucky_zodiac_sign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscopelucky',
            old_name='month_date',
            new_name='week_monday',
        ),
        migrations.RenameField(
            model_name='horoscopelucky',
            old_name='week_date',
            new_name='week_sunday',
        ),
        migrations.AlterField(
            model_name='horoscopelucky',
            name='horoscope_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10),
        ),
    ]
