# Generated by Django 5.1.7 on 2025-04-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_month_date_horoscopelucky_week_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscopelucky',
            old_name='week_monday',
            new_name='monday_date',
        ),
        migrations.RenameField(
            model_name='horoscopelucky',
            old_name='week_sunday',
            new_name='sunday_date',
        ),
    ]
